FROM condaforge/miniforge3 AS conda

COPY environment.yml .
COPY conda-lock.yml .

RUN --mount=type=cache,target=/opt/conda/pkgs \
    mamba create --copy -p /env --file environment.yml

COPY app /code/app
WORKDIR /code

RUN /env/bin/python -m pip cache purge || true

EXPOSE 8001

CMD ["/env/bin/python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
