name: cadet-api
channels:
  - conda-forge
dependencies:
  - cadet
  - uvicorn
  - uv
  - gunicorn
  - pip
  - dill
  - fastapi
  - python-dotenv
  - requests
  - cryptography
  - pytest
  - pip:
      - cadet-process
